FORTRAN        = gfortran
CPLUSPLUS      = g++
CPLUSPLUS_MPI  = mpicxx

LAPACK_DIR     = /usr/local
FFTW_DIR       = /usr/local
BOOST_DIR      = /usr/local
ELPA_DIR       = /usr/local
CEREAL_DIR     = /usr/local
SCALAPACK_DIR  = /usr/local

OBJ_DIR = obj
NP      = 4
