on: [push, pull_request]
jobs:
  build_dockerfile:
    runs-on: ubuntu-latest
    continue-on-error: true
    # if: ${{ github.repository_owner == 'deepmodeling' }}
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          #username: ${{ github.repository_owner }}
          username: deepmodeling
          password: ${{ secrets.PAT }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/deepmodeling/abacus-development-kit:gcc8
          cache-from: type=registry,ref=ghcr.io/deepmodeling/abacus-development-kit:gcc8
          cache-to: type=inline

  build_and_test:
    runs-on: ubuntu-latest
    container: ghcr.io/deepmodeling/abacus-development-kit:gcc8
    needs: build_dockerfile
    env:
      PREFIX: ABACUS.develop
      BIN: ABACUS
    steps:
      - name: Download source codes
        uses: actions/checkout@v2
      - name: Build
        run: cd ${PREFIX} && mkdir build && cd build && cmake ../cmake && make -j4 && make install
      - name: Test single
        run: |
          cd ${PREFIX}/tests/
          cd 103_PW_15_CS_CF/
          ${BIN}
